mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
proxies:
- name: ⚠️ Lite-версия подписки устарела
  type: vless
  server: 0.0.0.0
  port: 1
  uuid: 00000000-0000-0000-0000-000000000000
  udp: true
  skip-cert-verify: false
  tls: true
  servername: zieng2.org
  client-fingerprint: chrome
  reality-opts:
    public-key: dE3wtv44FXcZGAp0MYiYYa79zxJlcVNmPN5t8qa0cTs
    short-id: 7a69656e6732
- name: Обновите ссылку на актуальную
  type: vless
  server: 0.0.0.0
  port: 2
  uuid: 00000000-0000-0000-0000-000000000000
  udp: true
  skip-cert-verify: false
  tls: true
  servername: zieng2.org
  client-fingerprint: chrome
  reality-opts:
    public-key: 2nubdAYgPRiVoB88RsXViyhp9TchqXY6WmQtFELv4nA
    short-id: 7a69656e6733
- name: https://github.com/zieng2/wl
  type: vless
  server: 0.0.0.0
  port: 3
  uuid: 00000000-0000-0000-0000-000000000000
  udp: true
  skip-cert-verify: false
  tls: true
  servername: zieng2.org
  client-fingerprint: chrome
  reality-opts:
    public-key: ssvmqwroFTDVi1v2Jkmqlo8QoArjaLyJ17lq6BhIlzo
    short-id: 7a69656e6734
- name: https://t.me/zieng2
  type: vless
  server: 0.0.0.0
  port: 4
  uuid: 00000000-0000-0000-0000-000000000000
  udp: true
  skip-cert-verify: false
  tls: true
  servername: zieng2.org
  client-fingerprint: chrome
  reality-opts:
    public-key: ACX4SiuP3kQfZmK6VIirXhBhgafl3CEjLZGITY2MGVg
    short-id: 7a69656e6735
- name: '🇦🇹 Austria — #7'
  type: vless
  server: 188.68.218.205
  port: 443
  uuid: 6aaa7d1d-8b35-4fd2-ae60-0129ad624935
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: static-basket-01.wbbasket.ru
  client-fingerprint: safari
  reality-opts:
    public-key: 8dPBbufX7ST4NrD8Etatp_FR_mbd38vXa2ZXCVLxjQ4
    short-id: 0fc62d3cd3089adb
  grpc-opts:
    grpc-service-name: grpc
- name: '🇦🇹 Austria — #8'
  type: vless
  server: 188.68.218.205
  port: 443
  uuid: 6aaa7d1d-8b35-4fd2-ae60-0129ad624935
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: static-basket-01.wbbasket.ru
  client-fingerprint: edge
  reality-opts:
    public-key: 8dPBbufX7ST4NrD8Etatp_FR_mbd38vXa2ZXCVLxjQ4
    short-id: 0fc62d3cd3089adb
  grpc-opts:
    grpc-service-name: grpc
- name: '🇦🇹 Austria — #9'
  type: vless
  server: 188.68.218.205
  port: 443
  uuid: 6aaa7d1d-8b35-4fd2-ae60-0129ad624935
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: static-basket-01.wbbasket.ru
  client-fingerprint: firefox
  reality-opts:
    public-key: 8dPBbufX7ST4NrD8Etatp_FR_mbd38vXa2ZXCVLxjQ4
    short-id: 0fc62d3cd3089adb
  grpc-opts:
    grpc-service-name: grpc
- name: '🇦🇹 Austria — #10'
  type: vless
  server: 188.68.218.205
  port: 443
  uuid: 6aaa7d1d-8b35-4fd2-ae60-0129ad624935
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: static-basket-01.wbbasket.ru
  client-fingerprint: chrome
  reality-opts:
    public-key: 8dPBbufX7ST4NrD8Etatp_FR_mbd38vXa2ZXCVLxjQ4
    short-id: 0fc62d3cd3089adb
  grpc-opts:
    grpc-service-name: grpc
- name: '🇦🇹 Austria — #11'
  type: vless
  server: 188.68.218.205
  port: 443
  uuid: 6aaa7d1d-8b35-4fd2-ae60-0129ad624935
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: static-basket-01.wbbasket.ru
  client-fingerprint: qq
  reality-opts:
    public-key: 8dPBbufX7ST4NrD8Etatp_FR_mbd38vXa2ZXCVLxjQ4
    short-id: 0fc62d3cd3089adb
  grpc-opts:
    grpc-service-name: grpc
- name: '🇦🇹 Austria — #12'
  type: vless
  server: 188.68.218.205
  port: 443
  uuid: 6aaa7d1d-8b35-4fd2-ae60-0129ad624935
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: static-basket-01.wbbasket.ru
  client-fingerprint: ios
  reality-opts:
    public-key: 8dPBbufX7ST4NrD8Etatp_FR_mbd38vXa2ZXCVLxjQ4
    short-id: 0fc62d3cd3089adb
  grpc-opts:
    grpc-service-name: grpc
- name: '🇨🇭 Switzerland — #13'
  type: vless
  server: 193.124.125.79
  port: 161
  uuid: a4dd3787-cc60-4560-91f8-243ffd4f9b82
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: avito.st
  client-fingerprint: qq
  reality-opts:
    public-key: D5ttWzeUeEo0oKchjhHGY7Z8jFrAB-BOz6kdQpCrZg0
    short-id: ''
  grpc-opts:
    grpc-service-name: lv3grpc
- name: '🇨🇭 Switzerland — #14'
  type: vless
  server: 193.124.125.79
  port: 161
  uuid: b4574679-62dd-4f3c-ba90-51864c4380a3
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: avito.st
  client-fingerprint: qq
  reality-opts:
    public-key: D5ttWzeUeEo0oKchjhHGY7Z8jFrAB-BOz6kdQpCrZg0
    short-id: ''
  grpc-opts:
    grpc-service-name: lv3grpc
- name: '🇨🇭 Switzerland — #15'
  type: vless
  server: 193.124.125.79
  port: 161
  uuid: 3e46babc-192b-4f61-84ad-36aed8714b6d
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: avito.st
  client-fingerprint: qq
  reality-opts:
    public-key: D5ttWzeUeEo0oKchjhHGY7Z8jFrAB-BOz6kdQpCrZg0
    short-id: ''
  grpc-opts:
    grpc-service-name: lv3grpc
- name: '🇨🇭 Switzerland — #16'
  type: vless
  server: 193.124.125.79
  port: 161
  uuid: 908a8661-6882-450b-b9d5-de8231c43645
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: avito.st
  client-fingerprint: qq
  reality-opts:
    public-key: D5ttWzeUeEo0oKchjhHGY7Z8jFrAB-BOz6kdQpCrZg0
    short-id: ''
  grpc-opts:
    grpc-service-name: lv3grpc
- name: '🇨🇭 Switzerland — #17'
  type: vless
  server: 193.124.125.79
  port: 161
  uuid: 00f6064c-1407-4e44-876d-324b19fd307b
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: avito.st
  client-fingerprint: qq
  reality-opts:
    public-key: D5ttWzeUeEo0oKchjhHGY7Z8jFrAB-BOz6kdQpCrZg0
    short-id: ''
  grpc-opts:
    grpc-service-name: lv3grpc
- name: '🇨🇭 Switzerland — #18'
  type: vless
  server: 193.124.125.79
  port: 161
  uuid: 3e46babc-192b-4f61-84ad-36aed8714b6d
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: avito.st
  client-fingerprint: firefox
  reality-opts:
    public-key: D5ttWzeUeEo0oKchjhHGY7Z8jFrAB-BOz6kdQpCrZg0
    short-id: ''
  grpc-opts:
    grpc-service-name: lv3grpc
- name: '🇨🇭 Switzerland — #19'
  type: vless
  server: 193.124.125.79
  port: 161
  uuid: a4dd3787-cc60-4560-91f8-243ffd4f9b82
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: avito.st
  client-fingerprint: firefox
  reality-opts:
    public-key: D5ttWzeUeEo0oKchjhHGY7Z8jFrAB-BOz6kdQpCrZg0
    short-id: ''
  grpc-opts:
    grpc-service-name: lv3grpc
- name: '🇨🇭 Switzerland — #20'
  type: vless
  server: 193.124.125.79
  port: 161
  uuid: f1f77dc6-17e8-4267-a054-1dee7501ff61
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: avito.st
  client-fingerprint: firefox
  reality-opts:
    public-key: D5ttWzeUeEo0oKchjhHGY7Z8jFrAB-BOz6kdQpCrZg0
    short-id: ''
  grpc-opts:
    grpc-service-name: lv3grpc
- name: '🇨🇭 Switzerland — #21'
  type: vless
  server: 193.124.125.79
  port: 161
  uuid: bcd5c692-5979-4133-8c3c-ca0c94f7063f
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: avito.st
  client-fingerprint: edge
  reality-opts:
    public-key: D5ttWzeUeEo0oKchjhHGY7Z8jFrAB-BOz6kdQpCrZg0
    short-id: ''
  grpc-opts:
    grpc-service-name: lv3grpc
- name: '🇨🇭 Switzerland — #22'
  type: vless
  server: 193.124.125.79
  port: 161
  uuid: b4574679-62dd-4f3c-ba90-51864c4380a3
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: avito.st
  client-fingerprint: firefox
  reality-opts:
    public-key: D5ttWzeUeEo0oKchjhHGY7Z8jFrAB-BOz6kdQpCrZg0
    short-id: ''
  grpc-opts:
    grpc-service-name: lv3grpc
- name: '🇨🇭 Switzerland — #23'
  type: vless
  server: 193.124.125.79
  port: 161
  uuid: a4dd3787-cc60-4560-91f8-243ffd4f9b82
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: avito.st
  client-fingerprint: ios
  reality-opts:
    public-key: D5ttWzeUeEo0oKchjhHGY7Z8jFrAB-BOz6kdQpCrZg0
    short-id: ''
  grpc-opts:
    grpc-service-name: lv3grpc
- name: '🇨🇭 Switzerland — #24'
  type: vless
  server: 193.124.125.79
  port: 161
  uuid: bcd5c692-5979-4133-8c3c-ca0c94f7063f
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: avito.st
  client-fingerprint: safari
  reality-opts:
    public-key: D5ttWzeUeEo0oKchjhHGY7Z8jFrAB-BOz6kdQpCrZg0
    short-id: ''
  grpc-opts:
    grpc-service-name: lv3grpc
- name: '🇨🇭 Switzerland — #25'
  type: vless
  server: 193.124.125.79
  port: 161
  uuid: f1f77dc6-17e8-4267-a054-1dee7501ff61
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: avito.st
  client-fingerprint: edge
  reality-opts:
    public-key: D5ttWzeUeEo0oKchjhHGY7Z8jFrAB-BOz6kdQpCrZg0
    short-id: ''
  grpc-opts:
    grpc-service-name: lv3grpc
- name: '🇨🇭 Switzerland — #26'
  type: vless
  server: 193.124.125.79
  port: 161
  uuid: bcd5c692-5979-4133-8c3c-ca0c94f7063f
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: avito.st
  client-fingerprint: firefox
  reality-opts:
    public-key: D5ttWzeUeEo0oKchjhHGY7Z8jFrAB-BOz6kdQpCrZg0
    short-id: ''
  grpc-opts:
    grpc-service-name: lv3grpc
- name: '🇨🇭 Switzerland — #27'
  type: vless
  server: 188.68.216.38
  port: 9882
  uuid: 5d16ac22-6eea-426f-b778-6f4c2961faef
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: dl.google.com
  client-fingerprint: qq
  reality-opts:
    public-key: bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU
    short-id: aa
  grpc-opts:
    grpc-service-name: grpc-tunnel
- name: '🇨🇿 Czechia — #28'
  type: vless
  server: 78.159.247.205
  port: 443
  uuid: 92089155-6602-4122-86d4-fe6de20e8c4d
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: kinopoisk.ru
  client-fingerprint: firefox
  reality-opts:
    public-key: NsTRRl4ofT64w0VwmkpOWE8yfiXLcEqgwgi-9SGnXTA
    short-id: a1b2c3d4
- name: '🇨🇿 Czechia — #29'
  type: vless
  server: 78.159.247.170
  port: 443
  uuid: 92089155-6602-4122-86d4-fe6de20e8c4d
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: kinopoisk.ru
  client-fingerprint: firefox
  reality-opts:
    public-key: NsTRRl4ofT64w0VwmkpOWE8yfiXLcEqgwgi-9SGnXTA
    short-id: a1b2c3d4
- name: '🇨🇿 Czechia — #30'
  type: vless
  server: 78.159.247.214
  port: 443
  uuid: 92089155-6602-4122-86d4-fe6de20e8c4d
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: kinopoisk.ru
  client-fingerprint: firefox
  reality-opts:
    public-key: NsTRRl4ofT64w0VwmkpOWE8yfiXLcEqgwgi-9SGnXTA
    short-id: a1b2c3d4
- name: '🇨🇿 Czechia — #31'
  type: vless
  server: 78.159.247.246
  port: 443
  uuid: 1852b02c-1828-40eb-81ff-4de3d097cb35
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: sb2.hat.onl
  client-fingerprint: chrome
  ws-opts:
    path: /ws
    headers:
      Host: sb2.hat.onl
- name: '🇩🇪 Germany — #32'
  type: vless
  server: 188.68.216.38
  port: 9891
  uuid: 5d16ac22-6eea-426f-b778-6f4c2961faef
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: dl.google.com
  client-fingerprint: firefox
  reality-opts:
    public-key: Dfgu8Ey0M8Hz4gXGZAwQ3H9jLt2HByVsjAOTWiuKDB0
    short-id: aabbccdd
  grpc-opts:
    grpc-service-name: grpc-tunnel
- name: '🇩🇪 Germany — #33'
  type: vless
  server: 188.68.216.38
  port: 9891
  uuid: 5d16ac22-6eea-426f-b778-6f4c2961faef
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: dl.google.com
  client-fingerprint: qq
  reality-opts:
    public-key: Dfgu8Ey0M8Hz4gXGZAwQ3H9jLt2HByVsjAOTWiuKDB0
    short-id: aabbccdd
  grpc-opts:
    grpc-service-name: grpc-tunnel
- name: '🇬🇧 United Kingdom — #34'
  type: vless
  server: 188.225.27.78
  port: 443
  uuid: 3b6a9df3-f1d1-4bc1-94a5-0d8f2d5512b1
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: max.ru
  client-fingerprint: firefox
  reality-opts:
    public-key: Rf2jgZShaYRQ2kh9nF79eB2KFcIdiYHwPWJyFKA_CWU
    short-id: ''
- name: '🇮🇸 Iceland — #35'
  type: vless
  server: 188.225.45.152
  port: 443
  uuid: 238e492b-bc20-4380-92b6-135d39112ca4
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: api8.eaglors.com
  client-fingerprint: qq
  reality-opts:
    public-key: Nb9IwEEhUHEbHSc6e5uYTjxDgN4ZExhDckM3OgYhj2o
    short-id: 52ccb3687fe0b7ec
- name: '🇮🇸 Iceland — #36'
  type: vless
  server: 188.225.45.152
  port: 443
  uuid: 238e492b-bc20-4380-92b6-135d39112ca4
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: api8.eaglors.com
  client-fingerprint: qq
  reality-opts:
    public-key: Nb9IwEEhUHEbHSc6e5uYTjxDgN4ZExhDckM3OgYhj2o
    short-id: 52ccb3687fe0b7ec
- name: '🇳🇱 The Netherlands — #37'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: fb67fd37-8d41-43a9-a093-c0b807fc5299
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: pr-media.pepro.site
  client-fingerprint: qq
  ws-opts:
    path: /ws
- name: '🇳🇱 The Netherlands — #38'
  type: vless
  server: 46.243.235.188
  port: 443
  uuid: ecf728d9-1555-4e12-b178-1d8bd98465e4
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: pool.dataroute.biz
  client-fingerprint: chrome
  reality-opts:
    public-key: _ilhBTibNauMOEUqylnlBAUTYiqHHtmEDXkx18SHCR4
    short-id: ''
- name: '🇳🇱 The Netherlands — #39'
  type: vless
  server: 46.243.235.188
  port: 443
  uuid: ecf728d9-1555-4e12-b178-1d8bd98465e4
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: pool.dataroute.biz
  client-fingerprint: qq
  reality-opts:
    public-key: _ilhBTibNauMOEUqylnlBAUTYiqHHtmEDXkx18SHCR4
    short-id: ''
- name: '🇳🇱 The Netherlands — #40'
  type: vless
  server: 185.141.227.155
  port: 20002
  uuid: 2b3e8750-b944-42fc-b36e-ec2c64b48a98
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: pool.dataroute.biz
  client-fingerprint: firefox
  reality-opts:
    public-key: _ilhBTibNauMOEUqylnlBAUTYiqHHtmEDXkx18SHCR4
    short-id: ''
- name: '🇳🇱 The Netherlands — #41'
  type: vless
  server: 46.243.235.188
  port: 443
  uuid: ecf728d9-1555-4e12-b178-1d8bd98465e4
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: pool.dataroute.biz
  client-fingerprint: firefox
  reality-opts:
    public-key: _ilhBTibNauMOEUqylnlBAUTYiqHHtmEDXkx18SHCR4
    short-id: ''
- name: '🇳🇱 The Netherlands — #42'
  type: vless
  server: 46.243.235.188
  port: 443
  uuid: ecf728d9-1555-4e12-b178-1d8bd98465e4
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: pool.dataroute.biz
  client-fingerprint: safari
  reality-opts:
    public-key: _ilhBTibNauMOEUqylnlBAUTYiqHHtmEDXkx18SHCR4
    short-id: ''
- name: '🇳🇱 The Netherlands — #43'
  type: vless
  server: 46.243.235.188
  port: 443
  uuid: ecf728d9-1555-4e12-b178-1d8bd98465e4
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: pool.dataroute.biz
  client-fingerprint: ios
  reality-opts:
    public-key: _ilhBTibNauMOEUqylnlBAUTYiqHHtmEDXkx18SHCR4
    short-id: ''
- name: '🇳🇱 The Netherlands — #44'
  type: vless
  server: 46.243.235.188
  port: 443
  uuid: ecf728d9-1555-4e12-b178-1d8bd98465e4
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: pool.dataroute.biz
  client-fingerprint: chrome
  reality-opts:
    public-key: _ilhBTibNauMOEUqylnlBAUTYiqHHtmEDXkx18SHCR4
    short-id: ''
- name: '🇳🇱 The Netherlands — #45'
  type: vless
  server: 185.141.227.155
  port: 20002
  uuid: 2b3e8750-b944-42fc-b36e-ec2c64b48a98
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: pool.dataroute.biz
  client-fingerprint: firefox
  reality-opts:
    public-key: _ilhBTibNauMOEUqylnlBAUTYiqHHtmEDXkx18SHCR4
    short-id: ''
- name: '🇳🇱 The Netherlands — #46'
  type: vless
  server: 85.198.70.200
  port: 14406
  uuid: 237f91bf-102e-4077-8cc3-baebccb42936
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: vk.ru
  client-fingerprint: firefox
  reality-opts:
    public-key: ldAmsl3dqTCUBmlmA8CS9ZnpznP6cFWj9AxNddWnbxY
    short-id: 1a2b3c4d5e6f7a8b
- name: '🇳🇱 The Netherlands — #47'
  type: vless
  server: 85.198.70.200
  port: 14406
  uuid: 237f91bf-102e-4077-8cc3-baebccb42936
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: vk.ru
  client-fingerprint: chrome
  reality-opts:
    public-key: ldAmsl3dqTCUBmlmA8CS9ZnpznP6cFWj9AxNddWnbxY
    short-id: 1a2b3c4d5e6f7a8b
- name: '🇳🇱 The Netherlands — #48'
  type: vless
  server: 31.131.255.35
  port: 9894
  uuid: 5d16ac22-6eea-426f-b778-6f4c2961faef
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: dl.google.com
  client-fingerprint: safari
  reality-opts:
    public-key: sm3E3hjmT6_Gmg_O9rBz4nfXYrHpnl6-LvcCp6T6_xc
    short-id: aa
  grpc-opts:
    grpc-service-name: grpc-tunnel
- name: '🇳🇱 The Netherlands — #49'
  type: vless
  server: 185.65.148.217
  port: 15443
  uuid: 3f63c86c-ac4a-4900-85cf-4fedf93c2ca5
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: rutube.ru
  client-fingerprint: chrome
  reality-opts:
    public-key: 10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc
    short-id: 43dcff53849b81e6
- name: '🇳🇱 The Netherlands — #50'
  type: vless
  server: 185.65.148.217
  port: 15443
  uuid: 3f63c86c-ac4a-4900-85cf-4fedf93c2ca5
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: rutube.ru
  client-fingerprint: edge
  reality-opts:
    public-key: 10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc
    short-id: 43dcff53849b81e6
- name: '🇳🇱 The Netherlands — #51'
  type: vless
  server: 185.65.148.217
  port: 15443
  uuid: 3f63c86c-ac4a-4900-85cf-4fedf93c2ca5
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: rutube.ru
  client-fingerprint: firefox
  reality-opts:
    public-key: 10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc
    short-id: 43dcff53849b81e6
- name: '🇳🇱 The Netherlands — #52'
  type: vless
  server: 185.65.148.217
  port: 15443
  uuid: 3f63c86c-ac4a-4900-85cf-4fedf93c2ca5
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: rutube.ru
  client-fingerprint: qq
  reality-opts:
    public-key: 10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc
    short-id: 43dcff53849b81e6
- name: '🇳🇱 The Netherlands — #53'
  type: vless
  server: 185.65.148.217
  port: 15443
  uuid: 3f63c86c-ac4a-4900-85cf-4fedf93c2ca5
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: rutube.ru
  client-fingerprint: safari
  reality-opts:
    public-key: 10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc
    short-id: 43dcff53849b81e6
- name: '🇳🇱 The Netherlands — #54'
  type: vless
  server: 185.141.227.155
  port: 20002
  uuid: 2b3e8750-b944-42fc-b36e-ec2c64b48a98
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: pool.dataroute.biz
  client-fingerprint: chrome
  reality-opts:
    public-key: _ilhBTibNauMOEUqylnlBAUTYiqHHtmEDXkx18SHCR4
    short-id: ''
proxy-groups:
- name: AUTO
  type: url-test
  include-all: true
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  timeout: 3000
  lazy: true
  max-failed-times: 5
  disable-udp: false
- name: MANUAL
  type: select
  include-all: true
rules:
- MATCH,AUTO
