mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
proxies:
- name: ⚠️ Lite-версия подписки устарела
  type: vless
  server: 0.0.0.0
  port: 1
  uuid: 00000000-0000-0000-0000-000000000000
  udp: true
  skip-cert-verify: false
  tls: true
  servername: zieng2.org
  client-fingerprint: chrome
  reality-opts:
    public-key: dE3wtv44FXcZGAp0MYiYYa79zxJlcVNmPN5t8qa0cTs
    short-id: 7a69656e6732
- name: Обновите ссылку на актуальную
  type: vless
  server: 0.0.0.0
  port: 2
  uuid: 00000000-0000-0000-0000-000000000000
  udp: true
  skip-cert-verify: false
  tls: true
  servername: zieng2.org
  client-fingerprint: chrome
  reality-opts:
    public-key: 2nubdAYgPRiVoB88RsXViyhp9TchqXY6WmQtFELv4nA
    short-id: 7a69656e6733
- name: https://github.com/zieng2/wl
  type: vless
  server: 0.0.0.0
  port: 3
  uuid: 00000000-0000-0000-0000-000000000000
  udp: true
  skip-cert-verify: false
  tls: true
  servername: zieng2.org
  client-fingerprint: chrome
  reality-opts:
    public-key: ssvmqwroFTDVi1v2Jkmqlo8QoArjaLyJ17lq6BhIlzo
    short-id: 7a69656e6734
- name: https://t.me/zieng2
  type: vless
  server: 0.0.0.0
  port: 4
  uuid: 00000000-0000-0000-0000-000000000000
  udp: true
  skip-cert-verify: false
  tls: true
  servername: zieng2.org
  client-fingerprint: chrome
  reality-opts:
    public-key: ACX4SiuP3kQfZmK6VIirXhBhgafl3CEjLZGITY2MGVg
    short-id: 7a69656e6735
- name: '🇨🇿 Czechia — #17'
  type: vless
  server: 85.239.34.16
  port: 7443
  uuid: b67ed271-5a34-4d07-9970-f8ba27ca2c8a
  udp: true
  skip-cert-verify: false
  tls: true
  servername: rutube.ru
  client-fingerprint: firefox
  reality-opts:
    public-key: 5QAO98ot2U7TcGs_f6EEaQjCzNOJLNHqPf6smYsdFVI
    short-id: d82fb387
- name: '🇩🇪 Germany — #18'
  type: vless
  server: 176.109.85.114
  port: 5555
  uuid: bea7a5db-bb02-4bcd-bece-62832eb1bc94
  udp: true
  skip-cert-verify: false
  tls: true
  servername: max.ru
  client-fingerprint: firefox
  reality-opts:
    public-key: SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc
    short-id: ''
- name: '🇩🇪 Germany — #19'
  type: vless
  server: 51.250.97.18
  port: 443
  uuid: 3a08bc4e-882f-4a0f-ab60-09a75c34b2cc
  udp: true
  skip-cert-verify: false
  tls: true
  servername: cdp.x5.ru
  client-fingerprint: safari
  reality-opts:
    public-key: wgXD4k3A16WR0aL63N9Mx8xoqFigJLyQWJXi-l3MPXI
    short-id: 8ec792bfd725be8a
- name: '🇩🇪 Germany — #20'
  type: vless
  server: 51.250.108.162
  port: 443
  uuid: 3a08bc4e-882f-4a0f-ab60-09a75c34b2cc
  udp: true
  skip-cert-verify: false
  tls: true
  servername: cdp.x5.ru
  client-fingerprint: safari
  reality-opts:
    public-key: wgXD4k3A16WR0aL63N9Mx8xoqFigJLyQWJXi-l3MPXI
    short-id: 8ec792bfd725be8a
- name: '🇩🇪 Germany — #21'
  type: vless
  server: 51.250.24.222
  port: 443
  uuid: 3a08bc4e-882f-4a0f-ab60-09a75c34b2cc
  udp: true
  skip-cert-verify: false
  tls: true
  servername: cdp.x5.ru
  client-fingerprint: safari
  reality-opts:
    public-key: wgXD4k3A16WR0aL63N9Mx8xoqFigJLyQWJXi-l3MPXI
    short-id: 8ec792bfd725be8a
- name: '🇩🇪 Germany — #22'
  type: vless
  server: 51.250.103.104
  port: 443
  uuid: 3a08bc4e-882f-4a0f-ab60-09a75c34b2cc
  udp: true
  skip-cert-verify: false
  tls: true
  servername: cdp.x5.ru
  client-fingerprint: safari
  reality-opts:
    public-key: wgXD4k3A16WR0aL63N9Mx8xoqFigJLyQWJXi-l3MPXI
    short-id: 8ec792bfd725be8a
- name: '🇩🇪 Germany — #23'
  type: vless
  server: 51.250.106.87
  port: 443
  uuid: 3a08bc4e-882f-4a0f-ab60-09a75c34b2cc
  udp: true
  skip-cert-verify: false
  tls: true
  servername: cdp.x5.ru
  client-fingerprint: safari
  reality-opts:
    public-key: wgXD4k3A16WR0aL63N9Mx8xoqFigJLyQWJXi-l3MPXI
    short-id: 8ec792bfd725be8a
- name: '🇩🇪 Germany — #24'
  type: vless
  server: 51.250.103.104
  port: 443
  uuid: a11932ba-0d66-46b2-bd71-7cd078d47dbf
  udp: true
  skip-cert-verify: false
  tls: true
  servername: cdp.x5.ru
  client-fingerprint: safari
  reality-opts:
    public-key: wgXD4k3A16WR0aL63N9Mx8xoqFigJLyQWJXi-l3MPXI
    short-id: 8ec792bfd725be8a
- name: '🇩🇪 Germany — #25'
  type: vless
  server: 51.250.24.222
  port: 443
  uuid: a11932ba-0d66-46b2-bd71-7cd078d47dbf
  udp: true
  skip-cert-verify: false
  tls: true
  servername: cdp.x5.ru
  client-fingerprint: safari
  reality-opts:
    public-key: wgXD4k3A16WR0aL63N9Mx8xoqFigJLyQWJXi-l3MPXI
    short-id: 8ec792bfd725be8a
- name: '🇩🇪 Germany — #26'
  type: vless
  server: 51.250.106.87
  port: 443
  uuid: a11932ba-0d66-46b2-bd71-7cd078d47dbf
  udp: true
  skip-cert-verify: false
  tls: true
  servername: cdp.x5.ru
  client-fingerprint: safari
  reality-opts:
    public-key: wgXD4k3A16WR0aL63N9Mx8xoqFigJLyQWJXi-l3MPXI
    short-id: 8ec792bfd725be8a
- name: '🇩🇪 Germany — #27'
  type: vless
  server: 51.250.102.69
  port: 443
  uuid: a11932ba-0d66-46b2-bd71-7cd078d47dbf
  udp: true
  skip-cert-verify: false
  tls: true
  servername: cdp.x5.ru
  client-fingerprint: safari
  reality-opts:
    public-key: wgXD4k3A16WR0aL63N9Mx8xoqFigJLyQWJXi-l3MPXI
    short-id: 8ec792bfd725be8a
- name: '🇩🇪 Germany — #28'
  type: vless
  server: 51.250.102.69
  port: 443
  uuid: 3a08bc4e-882f-4a0f-ab60-09a75c34b2cc
  udp: true
  skip-cert-verify: false
  tls: true
  servername: cdp.x5.ru
  client-fingerprint: safari
  reality-opts:
    public-key: wgXD4k3A16WR0aL63N9Mx8xoqFigJLyQWJXi-l3MPXI
    short-id: 8ec792bfd725be8a
- name: '🇩🇪 Germany — #29'
  type: vless
  server: 51.250.97.18
  port: 443
  uuid: a11932ba-0d66-46b2-bd71-7cd078d47dbf
  udp: true
  skip-cert-verify: false
  tls: true
  servername: cdp.x5.ru
  client-fingerprint: safari
  reality-opts:
    public-key: wgXD4k3A16WR0aL63N9Mx8xoqFigJLyQWJXi-l3MPXI
    short-id: 8ec792bfd725be8a
- name: '🇳🇱 The Netherlands — #30'
  type: vless
  server: 51.250.108.162
  port: 443
  uuid: a11932ba-0d66-46b2-bd71-7cd078d47dbf
  udp: true
  skip-cert-verify: false
  tls: true
  servername: cdp.x5.ru
  client-fingerprint: safari
  reality-opts:
    public-key: wgXD4k3A16WR0aL63N9Mx8xoqFigJLyQWJXi-l3MPXI
    short-id: 8ec792bfd725be8a
- name: '🇳🇱 The Netherlands — #31'
  type: vless
  server: 158.160.198.162
  port: 443
  uuid: a5ea9247-79f3-4655-aece-3fb51e1e669e
  udp: true
  skip-cert-verify: false
  tls: true
  servername: rezerv11.yunus.guru
  client-fingerprint: firefox
  reality-opts:
    public-key: 6QIHdF1dvSK8mDPOeWXvGIqJmZ2ySq5fyc7N15h1WFE
    short-id: 34256b39b4ebb864
- name: '🇳🇱 The Netherlands — #32'
  type: vless
  server: 158.160.199.123
  port: 443
  uuid: a5ea9247-79f3-4655-aece-3fb51e1e669e
  udp: true
  skip-cert-verify: false
  tls: true
  servername: rezerv8.yunus.guru
  client-fingerprint: firefox
  reality-opts:
    public-key: 6QIHdF1dvSK8mDPOeWXvGIqJmZ2ySq5fyc7N15h1WFE
    short-id: 34256b39b4ebb864
- name: '🇸🇪 Sweden — #33'
  type: vless
  server: 109.120.188.54
  port: 443
  uuid: 4e5017e0-07da-48ef-a882-fa26a845ead6
  udp: true
  skip-cert-verify: false
  tls: true
  servername: ads.x5.ru
  client-fingerprint: edge
  reality-opts:
    public-key: 4woJiVyGtLro6qRQdUcM2EJDHI3CLOeeE-knmSHk8lE
    short-id: 1ca44564cda56661
- name: '🇸🇪 Sweden — #34'
  type: vless
  server: 109.120.188.54
  port: 443
  uuid: 4e5017e0-07da-48ef-a882-fa26a845ead6
  udp: true
  skip-cert-verify: false
  tls: true
  servername: ads.x5.ru
  client-fingerprint: firefox
  reality-opts:
    public-key: 4woJiVyGtLro6qRQdUcM2EJDHI3CLOeeE-knmSHk8lE
    short-id: 1ca44564cda56661
- name: '🇸🇪 Sweden — #35'
  type: vless
  server: 109.120.188.54
  port: 443
  uuid: 4e5017e0-07da-48ef-a882-fa26a845ead6
  udp: true
  skip-cert-verify: false
  tls: true
  servername: ads.x5.ru
  client-fingerprint: qq
  reality-opts:
    public-key: 4woJiVyGtLro6qRQdUcM2EJDHI3CLOeeE-knmSHk8lE
    short-id: 1ca44564cda56661
- name: '🇸🇪 Sweden — #36'
  type: vless
  server: 194.87.143.111
  port: 443
  uuid: ff19693c-11f3-4df9-8713-79a85a5ca090
  udp: true
  skip-cert-verify: false
  tls: true
  servername: se.sellflow.org
  client-fingerprint: firefox
  reality-opts:
    public-key: SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc
    short-id: ''
- name: '🇸🇪 Sweden — #37'
  type: vless
  server: 158.160.92.193
  port: 8443
  uuid: d757aa0d-77a7-0457-8442-7b9ba9294dbf
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: yastatic.net
  client-fingerprint: firefox
  reality-opts:
    public-key: -IYdVZN6tM8hKc6QXD7MNL8qiT_zjIHlCciyrDLcqSQ
    short-id: ccd4a76a26
  grpc-opts:
    grpc-service-name: grpc
- name: '🇸🇬 Singapore — #38'
  type: vless
  server: 31.76.34.85
  port: 443
  uuid: be018243-71b9-4e87-a6d0-db512d31c554
  udp: true
  skip-cert-verify: false
  tls: true
  servername: ya.ru
  client-fingerprint: firefox
  reality-opts:
    public-key: Kk3tSi31p89ZivGdW0El-2MDshu_ILzK6h-xVnacT34
    short-id: cd0aca5fd14e7546
- name: '🇺🇸 United States — #39'
  type: vless
  server: 155.212.140.116
  port: 48350
  uuid: b05346a9-4d13-41a4-8d2a-6b7b64e73ffc
  udp: true
  skip-cert-verify: false
  tls: true
  servername: stats.vk-portal.net
  client-fingerprint: firefox
  reality-opts:
    public-key: Ea23HWLvV6k7UjJ8xCsUH2UI0oyasSLjXV84aTXQ6Uk
    short-id: ''
- name: '🇺🇸 United States — #40'
  type: vless
  server: 78.41.111.87
  port: 443
  uuid: 5bba42b3-35a4-443d-a488-6ecf6d7f74c8
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: s46724.cdn.ngenix.net
  client-fingerprint: chrome
  ws-opts:
    path: /api/user
- name: '🇺🇸 United States — #41'
  type: vless
  server: 194.87.143.111
  port: 443
  uuid: ff19693c-11f3-4df9-8713-79a85a5ca090
  udp: true
  skip-cert-verify: false
  tls: true
  servername: ai.sellflow.org
  client-fingerprint: firefox
  reality-opts:
    public-key: SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc
    short-id: ''
- name: '🇺🇸 United States — #42'
  type: vless
  server: 78.41.111.87
  port: 443
  uuid: 63a5da25-822a-4b32-89b4-27655b3abc8b
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: s46724.cdn.ngenix.net
  client-fingerprint: chrome
  ws-opts:
    path: /api/user
- name: '🇺🇸 United States — #43'
  type: vless
  server: 78.41.111.87
  port: 443
  uuid: 7dedeec9-6a88-4089-91a9-bf7157b1b48f
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: s46724.cdn.ngenix.net
  client-fingerprint: chrome
  ws-opts:
    path: /api/user
- name: https://t.me/zieng2
  type: vless
  server: 0.0.0.0
  port: 4
  uuid: 00000000-0000-0000-0000-000000000000
  udp: true
  skip-cert-verify: false
  tls: true
  servername: zieng2.org
  client-fingerprint: chrome
  reality-opts:
    public-key: ACX4SiuP3kQfZmK6VIirXhBhgafl3CEjLZGITY2MGVg
    short-id: 7a69656e6735
- name: https://github.com/zieng2/wl
  type: vless
  server: 0.0.0.0
  port: 3
  uuid: 00000000-0000-0000-0000-000000000000
  udp: true
  skip-cert-verify: false
  tls: true
  servername: zieng2.org
  client-fingerprint: chrome
  reality-opts:
    public-key: ssvmqwroFTDVi1v2Jkmqlo8QoArjaLyJ17lq6BhIlzo
    short-id: 7a69656e6734
- name: Обновите ссылку на актуальную
  type: vless
  server: 0.0.0.0
  port: 2
  uuid: 00000000-0000-0000-0000-000000000000
  udp: true
  skip-cert-verify: false
  tls: true
  servername: zieng2.org
  client-fingerprint: chrome
  reality-opts:
    public-key: 2nubdAYgPRiVoB88RsXViyhp9TchqXY6WmQtFELv4nA
    short-id: 7a69656e6733
- name: ⚠️ Lite-версия подписки устарела
  type: vless
  server: 0.0.0.0
  port: 1
  uuid: 00000000-0000-0000-0000-000000000000
  udp: true
  skip-cert-verify: false
  tls: true
  servername: zieng2.org
  client-fingerprint: chrome
  reality-opts:
    public-key: dE3wtv44FXcZGAp0MYiYYa79zxJlcVNmPN5t8qa0cTs
    short-id: 7a69656e6732
proxy-groups:
- name: AUTO
  type: url-test
  include-all: true
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  timeout: 3000
  lazy: true
  max-failed-times: 5
  disable-udp: false
- name: MANUAL
  type: select
  include-all: true
rules:
- MATCH,AUTO
