mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
proxies:
- name: ⚠️ Lite-версия подписки устарела
  type: vless
  server: 0.0.0.0
  port: 1
  uuid: 00000000-0000-0000-0000-000000000000
  udp: true
  skip-cert-verify: false
  tls: true
  servername: zieng2.org
  client-fingerprint: chrome
  reality-opts:
    public-key: dE3wtv44FXcZGAp0MYiYYa79zxJlcVNmPN5t8qa0cTs
    short-id: 7a69656e6732
- name: Обновите ссылку на актуальную
  type: vless
  server: 0.0.0.0
  port: 2
  uuid: 00000000-0000-0000-0000-000000000000
  udp: true
  skip-cert-verify: false
  tls: true
  servername: zieng2.org
  client-fingerprint: chrome
  reality-opts:
    public-key: 2nubdAYgPRiVoB88RsXViyhp9TchqXY6WmQtFELv4nA
    short-id: 7a69656e6733
- name: https://github.com/zieng2/wl
  type: vless
  server: 0.0.0.0
  port: 3
  uuid: 00000000-0000-0000-0000-000000000000
  udp: true
  skip-cert-verify: false
  tls: true
  servername: zieng2.org
  client-fingerprint: chrome
  reality-opts:
    public-key: ssvmqwroFTDVi1v2Jkmqlo8QoArjaLyJ17lq6BhIlzo
    short-id: 7a69656e6734
- name: https://t.me/zieng2
  type: vless
  server: 0.0.0.0
  port: 4
  uuid: 00000000-0000-0000-0000-000000000000
  udp: true
  skip-cert-verify: false
  tls: true
  servername: zieng2.org
  client-fingerprint: chrome
  reality-opts:
    public-key: ACX4SiuP3kQfZmK6VIirXhBhgafl3CEjLZGITY2MGVg
    short-id: 7a69656e6735
- name: '🇩🇪 Germany — #24'
  type: vless
  server: 37.18.14.168
  port: 10654
  uuid: 953358cb-82ba-4296-960d-6d2ec3468f4c
  udp: true
  skip-cert-verify: false
  network: xhttp
  tls: true
  servername: bl3fk52.sysopnova.art
  client-fingerprint: firefox
  reality-opts:
    public-key: ds10ztOlMn8xfeIKEQ1m3I-tdem-abZbHKtJCU13CQM
    short-id: 5c3fb122
- name: '🇩🇪 Germany — #25'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: chrome
  ws-opts:
    path: /ws
    headers:
      Host: media-se.compressor.work
- name: '🇩🇪 Germany — #26'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: edge
  ws-opts:
    path: /ws
    headers:
      Host: media-se.compressor.work
- name: '🇩🇪 Germany — #27'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: ios
  ws-opts:
    path: /ws
    headers:
      Host: media-se.compressor.work
- name: '🇩🇪 Germany — #28'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: safari
  ws-opts:
    path: /ws
    headers:
      Host: media-se.compressor.work
- name: '🇩🇪 Germany — #29'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: android
  ws-opts:
    path: /ws
- name: '🇩🇪 Germany — #30'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: chrome
  ws-opts:
    path: /ws
- name: '🇩🇪 Germany — #31'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: edge
  ws-opts:
    path: /ws
- name: '🇩🇪 Germany — #32'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: firefox
  ws-opts:
    path: /ws
- name: '🇩🇪 Germany — #33'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: ios
  ws-opts:
    path: /ws
- name: '🇩🇪 Germany — #34'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: qq
  ws-opts:
    path: /ws
- name: '🇩🇪 Germany — #35'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: safari
  ws-opts:
    path: /ws
- name: '🇩🇪 Germany — #36'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: chrome
  ws-opts:
    path: /ws
    headers:
      Host: 95.163.232.171
- name: '🇩🇪 Germany — #37'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: edge
  ws-opts:
    path: /ws
    headers:
      Host: 95.163.232.171
- name: '🇩🇪 Germany — #38'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: firefox
  ws-opts:
    path: /ws
    headers:
      Host: 95.163.232.171
- name: '🇩🇪 Germany — #39'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: qq
  ws-opts:
    path: /ws
    headers:
      Host: 95.163.232.171
- name: '🇩🇪 Germany — #40'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: safari
  ws-opts:
    path: /ws
    headers:
      Host: 95.163.232.171
- name: '🇩🇪 Germany — #41'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: chrome
  ws-opts:
    path: /ws
- name: '🇩🇪 Germany — #42'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: edge
  ws-opts:
    path: /ws
- name: '🇩🇪 Germany — #43'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: firefox
  ws-opts:
    path: /ws
- name: '🇩🇪 Germany — #44'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: qq
  ws-opts:
    path: /ws
- name: '🇩🇪 Germany — #45'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: safari
  ws-opts:
    path: /ws
- name: '🇩🇪 Germany — #46'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: firefox
  ws-opts:
    path: /ws
    headers:
      Host: 95.163.232.171
- name: '🇩🇪 Germany — #47'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: qq
  ws-opts:
    path: /ws
    headers:
      Host: 95.163.232.171
- name: '🇩🇪 Germany — #48'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: firefox
  ws-opts:
    path: /ws
    headers:
      Host: media-se.compressor.work
- name: '🇩🇪 Germany — #49'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: chrome
  ws-opts:
    path: /ws
    headers:
      Host: 95.163.232.171
- name: '🇩🇪 Germany — #50'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: random
  ws-opts:
    path: /ws
- name: '🇩🇪 Germany — #51'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: random
  ws-opts:
    path: /ws
    headers:
      Host: 95.163.232.171
- name: '🇩🇪 Germany — #52'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: random
  ws-opts:
    path: /ws
    headers:
      Host: media-se.compressor.work
- name: '🇩🇪 Germany — #53'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: random
  ws-opts:
    path: /ws
- name: '🇩🇪 Germany — #54'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: random
  ws-opts:
    path: /ws
    headers:
      Host: '['''']'
- name: '🇩🇪 Germany — #55'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: random
  ws-opts:
    path: /ws
    headers:
      Host: media-se.compressor.work
- name: '🇩🇪 Germany — #56'
  type: vless
  server: 95.163.232.171
  port: 14443
  uuid: 365de9e9-ba29-4819-af2d-766f9638e3be
  udp: true
  skip-cert-verify: false
  network: ws
  tls: true
  servername: media-se.compressor.work
  client-fingerprint: random
  ws-opts:
    path: /ws
    headers:
      Host: 95.163.232.171
- name: '🇫🇷 France — #57'
  type: vless
  server: 176.123.162.100
  port: 9880
  uuid: 5d16ac22-6eea-426f-b778-6f4c2961faef
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: dl.google.com
  client-fingerprint: firefox
  reality-opts:
    public-key: bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU
    short-id: ''
  grpc-opts:
    grpc-service-name: grpc-tunnel
- name: '🇫🇷 France — #58'
  type: vless
  server: 91.240.87.237
  port: 443
  uuid: 1b201db0-b373-455a-8ccd-fd624aaef8d3
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: fiae3.maxtelemost.com
  client-fingerprint: firefox
  reality-opts:
    public-key: J0SK1ic3YJvP1gac5m3KSVaUuK_bxFtqz0fh0uEdEw4
    short-id: '00000000'
- name: '🇫🇷 France — #59'
  type: vless
  server: 91.240.87.237
  port: 443
  uuid: 1b201db0-b373-455a-8ccd-fd624aaef8d3
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: fiae3.maxtelemost.com
  client-fingerprint: qq
  reality-opts:
    public-key: J0SK1ic3YJvP1gac5m3KSVaUuK_bxFtqz0fh0uEdEw4
    short-id: '00000000'
- name: '🇫🇷 France — #60'
  type: vless
  server: 91.240.87.237
  port: 443
  uuid: 1b201db0-b373-455a-8ccd-fd624aaef8d3
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: fiae3.maxtelemost.com
  client-fingerprint: random
  reality-opts:
    public-key: J0SK1ic3YJvP1gac5m3KSVaUuK_bxFtqz0fh0uEdEw4
    short-id: '00000000'
- name: '🇫🇷 France — #61'
  type: vless
  server: 91.240.87.237
  port: 443
  uuid: 1b201db0-b373-455a-8ccd-fd624aaef8d3
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: fiae3.maxtelemost.com
  client-fingerprint: chrome
  reality-opts:
    public-key: J0SK1ic3YJvP1gac5m3KSVaUuK_bxFtqz0fh0uEdEw4
    short-id: '00000000'
- name: '🇫🇷 France — #62'
  type: vless
  server: 91.240.87.237
  port: 443
  uuid: 1b201db0-b373-455a-8ccd-fd624aaef8d3
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: fiae3.maxtelemost.com
  client-fingerprint: safari
  reality-opts:
    public-key: J0SK1ic3YJvP1gac5m3KSVaUuK_bxFtqz0fh0uEdEw4
    short-id: '00000000'
- name: '🇫🇷 France — #63'
  type: vless
  server: 91.240.87.237
  port: 443
  uuid: e0a8c12c-6fe9-42a3-990e-abe2ea6e5605
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: fiae3.maxtelemost.com
  client-fingerprint: random
  reality-opts:
    public-key: J0SK1ic3YJvP1gac5m3KSVaUuK_bxFtqz0fh0uEdEw4
    short-id: '00000000'
- name: '🇫🇷 France — #64'
  type: vless
  server: 91.240.87.237
  port: 443
  uuid: e0a8c12c-6fe9-42a3-990e-abe2ea6e5605
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: fiae3.maxtelemost.com
  client-fingerprint: safari
  reality-opts:
    public-key: J0SK1ic3YJvP1gac5m3KSVaUuK_bxFtqz0fh0uEdEw4
    short-id: '00000000'
- name: '🇵🇱 Poland — #65'
  type: vless
  server: 176.123.161.222
  port: 9892
  uuid: 5d16ac22-6eea-426f-b778-6f4c2961faef
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: dl.google.com
  client-fingerprint: firefox
  reality-opts:
    public-key: bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU
    short-id: ''
  grpc-opts:
    grpc-service-name: grpc-tunnel
- name: '🇵🇱 Poland — #66'
  type: vless
  server: 188.225.79.44
  port: 443
  uuid: adc11f30-e4cb-4985-bf5e-f9ded69c019f
  udp: true
  skip-cert-verify: false
  network: raw
  tls: true
  servername: eh.vk.ru
  client-fingerprint: firefox
  reality-opts:
    public-key: fNfokzklCF4l_c8k8PciOCjm5ecNoF_sNLjEtaO-xzI
    short-id: db04ce8bdb8900f1
- name: '🇷🇸 Serbia — #67'
  type: vless
  server: 213.171.25.29
  port: 9889
  uuid: 5d16ac22-6eea-426f-b778-6f4c2961faef
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: dl.google.com
  client-fingerprint: firefox
  reality-opts:
    public-key: ycPIUcY6ci2yi7YA_OHc20e4gzxEdJTqpmeShxSuHRU
    short-id: aabb
  grpc-opts:
    grpc-service-name: grpc-tunnel
- name: '🇸🇪 Sweden — #68'
  type: vless
  server: 176.108.246.58
  port: 9881
  uuid: 5d16ac22-6eea-426f-b778-6f4c2961faef
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: dl.google.com
  client-fingerprint: chrome
  reality-opts:
    public-key: ycPIUcY6ci2yi7YA_OHc20e4gzxEdJTqpmeShxSuHRU
    short-id: ''
  grpc-opts:
    grpc-service-name: grpc-tunnel
- name: '🇸🇪 Sweden — #69'
  type: vless
  server: 176.108.246.110
  port: 9830
  uuid: 5d16ac22-6eea-426f-b778-6f4c2961faef
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: dl.google.com
  client-fingerprint: chrome
  reality-opts:
    public-key: bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU
    short-id: ''
  grpc-opts:
    grpc-service-name: grpc-tunnel
- name: '🇺🇸 United States — #70'
  type: vless
  server: 176.108.246.73
  port: 9873
  uuid: 5d16ac22-6eea-426f-b778-6f4c2961faef
  udp: true
  skip-cert-verify: false
  network: grpc
  tls: true
  servername: dl.google.com
  client-fingerprint: chrome
  reality-opts:
    public-key: bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU
    short-id: aabbccdd
  grpc-opts:
    grpc-service-name: grpc-tunnel
proxy-groups:
- name: AUTO
  type: url-test
  include-all: true
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  timeout: 3000
  lazy: true
  max-failed-times: 5
  disable-udp: false
- name: MANUAL
  type: select
  include-all: true
rules:
- MATCH,AUTO
